---
- name: Configure System Cryptography Policy (permanent)
  ansible.builtin.lineinfile:
    path: /etc/crypto-policies/config
    regexp: ^(?!#)(\S+)$
    line: '{{ var_system_crypto_policy }}'
    create: true

- name: Configure System Cryptography Policy (runtime)
  ansible.builtin.command: /usr/bin/update-crypto-policies --set {{ theforeman_custom_set_crypto_policy_var_system_crypto_policy }}
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0